# Generated by Django 4.2.4 on 2023-08-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animal1_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal1',
            old_name='lion',
            new_name='girraph',
        ),
    ]
