# Generated by Django 4.2.4 on 2023-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_rename_lion_animal1_girraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal1',
            name='login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
